# MD010/no-hard-tabs - Hard tabs
MD010: false

# MD013/line-length - Line length
MD013: false

# MD024/no-duplicate-heading/no-duplicate-header - Multiple headings with the same content
MD024: false

# MD033/no-inline-html - Inline HTML
MD033: false
