name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@6d3f514f44620b9d4488e380339edc0d9bbe2fba
      with:
        severity: error

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          cache-dependency-path: web/yarn.lock

      - name: Install Node packages
        run: yarn install --frozen-lockfile

      - name: Run ESLint
        run: yarn eslint js

  stylelint:
    name: Stylelint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          cache-dependency-path: web/yarn.lock

      - name: Install Node packages
        run: yarn install --frozen-lockfile

      - name: Run Stylelint
        run: yarn stylelint css/src/themes/*.css
